## Pandas
is the most popular Python library for data analysis, help dealing with data set and it will extract the data from that CSV into a DataFrame.

<img src='../data/pandas.png'>

### IMPORT OF Pandas :-
- import `pandas` as `pd`

In [1]:
import pandas as pd

#### Series & DataFrame

##### 1. Series:
 is considered column in an excel sheet.
##### 2. DataFrame:
 is a table, datasets arrange in rows and columns,
###### If a DataFrame is a table, a Series is a list.

<img src='../data/series-and-dataframe.width-1200.png'>

#### Create series
- created by loading the datasets from existing storage like CSV file, and Excel file. 
- can be created from the lists, dictionary, and from a scalar value etc.

In [2]:
pd.Series([3,2,0,1])

0    3
1    2
2    0
3    1
dtype: int64

In [3]:
#set index and name
pd.Series([3,2,0,1], index=['Day_1', 'Day_2','Day_3','Day_4'], name='Appels')

Day_1    3
Day_2    2
Day_3    0
Day_4    1
Name: Appels, dtype: int64

#### Create DataFrame
- can be created is an Empty Dataframe by calling a dataframe constructor.
- can be created from dict narray / lists ,Lists and List of Dicts.

In [3]:
# create dict
data = {
    'apples': [3, 2, 0, 1], 
    'oranges': [0, 3, 7, 2]
}

# keys are the column names 
# values are a list of entries
#then pass it to the pandas DataFrame constructor
mydata_frame= pd.DataFrame(data)
mydata_frame

   apples  oranges
0       3        0
1       2        3
2       0        7
3       1        2

In [5]:
# set index ( row labels)
import pandas as pd
mydata_frame= pd.DataFrame(data,index=['Day_1', 'Day_2','Day_3','Day_4'])
mydata_frame

       apples  oranges
Day_1       3        0
Day_2       2        3
Day_3       0        7
Day_4       1        2

###### Q: create a DataFrame by passing a list of dictionaries and the row indices.

### Reading data files
most of the time, we won't actually be creating our own data by hand. Instead, we'll be working with data that already exists.
Data can be stored in different forms and formats. as(txt,csv,Excel...)

- we can read data.csv (Comma-Separated Values) into a DataFrame by `pd.read_csv()`

In [4]:
'''
INTRO: DATA SET
Medium is one of the most famous tools for spreading knowledge about almost any field. 
It is widely used to published articles on ML, AI, and data science. 
This dataset is the collection of about 337 articles in such fields

'''
import pandas as pd
# change path your data
data_f=pd.read_csv(r'..\data\articles.csv')
data_f

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
...,...,...,...,...,...,...
332,Daniel Simmons,3.4K,8,https://itnext.io/you-can-build-a-neural-netwo...,You can build a neural network in JavaScript e...,Click here to share this article on LinkedIn »...
333,Eugenio Culurciello,2.8K,13,https://towardsdatascience.com/artificial-inte...,"Artificial Intelligence, AI in 2018 and beyond...",These are my opinions on where deep neural net...
334,Devin Soni,5.8K,4,https://towardsdatascience.com/spiking-neural-...,"Spiking Neural Networks, the Next Generation o...",Everyone who has been remotely tuned in to rec...
335,Carlos E. Perez,3.9K,7,https://medium.com/intuitionmachine/neurons-ar...,Surprise! Neurons are Now More Complex than We...,One of the biggest misconceptions around is th...
336,Nityesh Agarwal,2.4K,13,https://towardsdatascience.com/wth-does-a-neur...,“WTH does a neural network even learn??” — a n...,"I believe, we all have that psychologist/philo..."

 We can examine the contents of DataFrame using the ` head() ` command , which display the first five rows by default

In [5]:
data_f.head(5)

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...

we can use ` tail() `To see the last five rows

In [6]:
data_f.tail()

,author,claps,reading_time,link,title,text
332,Daniel Simmons,3.4K,8,https://itnext.io/you-can-build-a-neural-netwo...,You can build a neural network in JavaScript e...,Click here to share this article on LinkedIn »...
333,Eugenio Culurciello,2.8K,13,https://towardsdatascience.com/artificial-inte...,"Artificial Intelligence, AI in 2018 and beyond...",These are my opinions on where deep neural net...
334,Devin Soni,5.8K,4,https://towardsdatascience.com/spiking-neural-...,"Spiking Neural Networks, the Next Generation o...",Everyone who has been remotely tuned in to rec...
335,Carlos E. Perez,3.9K,7,https://medium.com/intuitionmachine/neurons-ar...,Surprise! Neurons are Now More Complex than We...,One of the biggest misconceptions around is th...
336,Nityesh Agarwal,2.4K,13,https://towardsdatascience.com/wth-does-a-neur...,“WTH does a neural network even learn??” — a n...,"I believe, we all have that psychologist/philo..."

In [8]:
#remove index
import pandas as pd
data_f=pd.read_csv('../data/articles.csv', index_col=0) # set index by columns (using name or index)
# we can use set_index()
#data_f.set_index('title')
data_f.head()

,claps,reading_time,link,title,text
author,,,,,
Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...
Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...

In [9]:
data_f=pd.read_csv('../data/articles.csv')

###### Understanding Our Data

- info() :

method display information about a DataFrame including the index dtype and column dtypes, non-null values and memory usage.

In [10]:
#info() function is used to get summary of the dataframe
data_f.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 337 entries, 0 to 336
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   author        337 non-null    object
 1   claps         337 non-null    object
 2   reading_time  337 non-null    int64
 3   link          337 non-null    object
 4   title         337 non-null    object
 5   text          337 non-null    object
dtypes: int64(1), object(5)
memory usage: 15.9+ KB

In [11]:
data_f=pd.read_csv('../data/articles.csv')
# using describe() "summary function"
data_f.describe()

       reading_time
count    337.000000
mean       9.700297
std        5.482855
min        2.000000
25%        6.000000
50%        8.000000
75%       13.000000
max       31.000000

In [12]:
data_f.reading_time.describe()

count    337.000000
mean       9.700297
std        5.482855
min        2.000000
25%        6.000000
50%        8.000000
75%       13.000000
max       31.000000
Name: reading_time, dtype: float64

In [14]:
data_f.author.describe()

count              337
unique             182
top       Adam Geitgey
freq                16
Name: author, dtype: object


<img src='data/Untitled.png'>

In [15]:
# To see a list of unique values we can use the unique() function
data_f.author.unique()
# note : Although repeated 'Justin Lee' 5 times , There are in unique array
# Each repeated value appears once in unique array

array(['Justin Lee', 'Conor Dewey', 'William Koehrsen', 'Gant Laborde',
       'Emmanuel Ameisen', 'Irhum Shafkat', 'Sam Drozdov',
       'Abhishek Parbhakar', 'Aman Dalmia', 'Sophia Arakelyan',
       'Dr. GP Pulipaka', 'Scott Santens', 'Adam Geitgey', 'Xiaohan Zeng',
       'Gil Fewster', 'David Venturi', 'Michael Jordan', 'Eran Kampf',
       'Oliver Lindberg', 'Xu Wenhao', 'Netflix Technology Blog',
       'Wolf Garbe', 'Paul Christiano', 'Robbie Tilton',
       'James Faghmous ', 'Datafiniti', 'Arjan Haring 🔮🔨', 'Eventbrite',
       'Akash Shende', 'Hrishikesh Huilgolkar', 'Shivon Zilis',
       'AirbnbEng', 'Yingjie Miao ', 'Pinterest Engineering',
       'Nikhil Dandekar', 'Jeff Smith', 'Chris Jagers', 'John Wittenauer',
       'Christopher Nguyen', 'Per Harald Borgen', 'Ahmed El Deeb',
       'Matt Fogel', 'Illia Polosukhin', 'Christophe Bourguignat',
       "I'Boss Potiwarakorn", 'samim', 'Arthur Juliani', 'Tal Perry',
       'Andrej Karpathy', 'Vishal Maini', 'Tim Anglade', 'Sophia Ciocca',
       'Dhruv Parthasarathy', 'Sebastian Heinz', 'Blaise Aguera y Arcas',
       'James Le', 'Mybridge', 'David Foster', 'George Seif',
       'Simon Greenman', 'Eugenio Culurciello', 'WiseWolf Fund',
       'Michael Solana', 'Lance Ulanoff', 'Matt Schlicht',
       'Milo Spencer-Harper', 'Greg Fish', 'Frank Diana', 'Wildcat2030',
       'Theo', 'x.ai', 'Roland Trimmel', 'Espen Waldal', 'Joe Johnston',
       'Nadav Gur', 'Pandorabots', 'Denny Vrandečić', 'Thaddeus Howze',
       'Tommy Thompson', 'Arik Sosman', 'Tony Aubé', "Matt O'Leary",
       'Tanay Jaipuria', 'Ben Brown', 'Rand Hindi', 'Chris Dixon',
       'François Chollet', 'Max Pechyonkin', 'Slav Ivanov',
       'Geoff Nesnow', 'Aman Agarwal', 'Gaurav Kaila', 'James Loy',
       'Chintan Trivedi', 'Leon Zhou', 'Erick Muzart Fonseca dos Santos',
       'Chris Kalahiki', 'Stefan Kojouharov', 'Francesco Gadaleta',
       'Jim Fleming', 'Christian Hernandez', 'Venture Scanner',
       'Derrick Harris', 'Kyle McDonald', 'Nathan Benaich',
       'Erik Hallström', 'Alexandr Honchar', 'Arvind N', 'Gary Marcus',
       'Bargava', 'Seth Weidman', 'Gabriel Aldamiz...', 'Sarthak Jain',
       'Emil Wallner', 'James JD Sutton', 'Kai Stinchcombe',
       'savedroid ICO', 'Brandon Morelli', 'Gabriel Jiménez',
       'Tyler Elliot Bettilyon', 'Berit Anderson', 'Sirui Li',
       'Diana Filippova', 'Peter Sweeney', 'E.C. McCarthy',
       'Jorge Camacho', 'Matt Wiese', "Tim O'Reilly", 'James Cooper',
       'Joel Leeman', 'Scott Smith', 'iDanScott', 'Josh', 'paulson',
       'Christopher Wolf Nordlinger', 'Louis Rosenfeld', 'Matt Harvey',
       'Vivek Yadav', 'Carlos Beltran', 'Oxford University',
       'Maciej Lipiec', 'Camron Godbout', 'Dominik Felix', 'Greg Gascon',
       'Keval Patel', 'Eduard Tyantov', 'Maruti Techlabs', 'Jerry Chen',
       'Gaurav Oberoi', 'Nick Bourdakos', 'Mark Johnson',
       'Leigh Alexander', 'Daniel Simmons', 'Logan Spears', 'Bharath Raj',
       'Daniel Rothmann', 'Amine Aoullay', 'Jonathan Balaban',
       'SAGAR SHARMA', 'Jae Duk Seo', 'Wallarm', 'Maryna Hlaiboroda',
       'Kelvin Li', 'Avinash Sharma V', "Elle O'Brien", 'Karl N.',
       'Nikolai Savas', 'Dr Ben Medlock', 'Nieves Ábalos', 'Rohan Kapur',
       'Shi Yan', 'Ross Goodwin', 'Eric Elliott', 'Waleed Abdulla', 'gk_',
       'nafrondel', 'Neelabh Pant', 'Favio Vázquez',
       'Oleksandr Savsunenko', 'Devin Soni', 'Carlos E. Perez',
       'Nityesh Agarwal'], dtype=object)

In [16]:
#To see a list of unique values and how often they occur in the dataset
data_f.author.value_counts()

Adam Geitgey           16
Slav Ivanov            10
Arthur Juliani         10
Milo Spencer-Harper     8
Dhruv Parthasarathy     6
                       ..
Rand Hindi              1
Ben Brown               1
Tanay Jaipuria          1
Tony Aubé              1
Nityesh Agarwal         1
Name: author, Length: 182, dtype: int64

In [16]:
data_f.shape

(337, 6)

###### Q:Display a summary of the basic information about  data ('medium_data.csv')

In [18]:
myDataFrame=pd.read_csv('../data/medium_data.csv')
myDataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6508 entries, 0 to 6507
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            6508 non-null   int64
 1   url           6508 non-null   object
 2   title         6508 non-null   object
 3   subtitle      3479 non-null   object
 4   image         6361 non-null   object
 5   claps         6508 non-null   int64
 6   responses     6508 non-null   object
 7   reading_time  6508 non-null   int64
 8   publication   6508 non-null   object
 9   date          6508 non-null   object
dtypes: int64(3), object(7)
memory usage: 508.6+ KB

# Accessing Data
Selecting specific values of a pandas DataFrame or Series to work on is in any data operation you'll run

In [17]:
import pandas as pd
data_f=pd.read_csv('../data/articles.csv')
data_f

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
...,...,...,...,...,...,...
332,Daniel Simmons,3.4K,8,https://itnext.io/you-can-build-a-neural-netwo...,You can build a neural network in JavaScript e...,Click here to share this article on LinkedIn »...
333,Eugenio Culurciello,2.8K,13,https://towardsdatascience.com/artificial-inte...,"Artificial Intelligence, AI in 2018 and beyond...",These are my opinions on where deep neural net...
334,Devin Soni,5.8K,4,https://towardsdatascience.com/spiking-neural-...,"Spiking Neural Networks, the Next Generation o...",Everyone who has been remotely tuned in to rec...
335,Carlos E. Perez,3.9K,7,https://medium.com/intuitionmachine/neurons-ar...,Surprise! Neurons are Now More Complex than We...,One of the biggest misconceptions around is th...
336,Nityesh Agarwal,2.4K,13,https://towardsdatascience.com/wth-does-a-neur...,“WTH does a neural network even learn??” — a n...,"I believe, we all have that psychologist/philo..."

###### 1.methode (Columns is attribute of object)
In Python, we can access the property of an object by accessing it as an attribute, Columns in a pandas DataFrame work in much the same way.

In [20]:
data_f.reading_time

0      11
1       7
2      11
3       7
4      11
       ..
332     8
333    13
334     4
335     7
336    13
Name: reading_time, Length: 337, dtype: int64

###### 2. methode (dataframe is dictionary)
in Python dictionary, we can access its values using the indexing ([]) operator.

- Note:
the indexing operator [] does have the advantage that it can handle column names with reserved characters in them (e.g. if we had a `Publishing house` column, `dataframe.Publishing house` wouldn't work).

In [18]:
data_f[['claps','link']]

    claps                                               link
0    8.3K  https://medium.com/swlh/chatbots-were-the-next...
1    1.4K  https://towardsdatascience.com/python-for-data...
2    2.8K  https://towardsdatascience.com/automated-featu...
3    1.3K  https://medium.freecodecamp.org/machine-learni...
4     935  https://blog.insightdatascience.com/reinforcem...
..    ...                                                ...
332  3.4K  https://itnext.io/you-can-build-a-neural-netwo...
333  2.8K  https://towardsdatascience.com/artificial-inte...
334  5.8K  https://towardsdatascience.com/spiking-neural-...
335  3.9K  https://medium.com/intuitionmachine/neurons-ar...
336  2.4K  https://towardsdatascience.com/wth-does-a-neur...

[337 rows x 2 columns]

###### Access entry

In [22]:
data_f['claps'][3]

'1.3K'

###### Accessor operators `loc`  and `iloc` 

- `iloc` we treat the dataset like a big matrix (a list of lists) , select data based on its numerical position in the data, this is called 'Index-based selection'.

- `loc` uses the information in the indices and ignores the dataset's indices, this is called ' label-based selection'.

In [19]:
data_f.head(2)

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...

In [24]:
data_f.iloc[0]

author                                                 Justin Lee
claps                                                        8.3K
reading_time                                                   11
link            https://medium.com/swlh/chatbots-were-the-next...
title           Chatbots were the next big thing: what happene...
text            Oh, how the headlines blared:\nChatbots were T...
Name: 0, dtype: object

In [25]:
data_f.head(2)

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...

In [26]:
data_f.iloc[:2]

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...

In [20]:
data_f.loc[:5]

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
5,Irhum Shafkat,2K,15,https://towardsdatascience.com/intuitively-und...,Intuitively Understanding Convolutions for Dee...,The advent of powerful and versatile deep lear...

**Q:** Select just the 'subtitle' and 'date' columns from the DataFrame `df`.

###### Conditional selection (==)
For example, what if we want to filter our articles to show only articles wirtten by Daniel Simmons

In [23]:
data_f=pd.read_csv('../data/articles.csv')
data_f.author=='Adam Geitgey'# return Series of True/False booleans based on the author of each record

0      False
1      False
2      False
3      False
4      False
       ...
332    False
333    False
334    False
335    False
336    False
Name: author, Length: 337, dtype: bool

In [24]:
#count them
sum(data_f.author=='Adam Geitgey')

16

In [25]:
data_f.loc[data_f.author=='Adam Geitgey']

,author,claps,reading_time,link,title,text
13,Adam Geitgey,35K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! – Adam Geitgey – Medium,Update: This article is part of a series. Chec...
14,Adam Geitgey,14.2K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 3: Deep Learning...,Update: This article is part of a series. Chec...
15,Adam Geitgey,15.2K,13,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 4: Modern Face R...,Update: This article is part of a series. Chec...
18,Adam Geitgey,10.4K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 2 – Adam Geitgey...,Update: This article is part of a series. Chec...
36,Adam Geitgey,35K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! – Adam Geitgey – Medium,Update: This article is part of a series. Chec...
56,Adam Geitgey,14.2K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 3: Deep Learning...,Update: This article is part of a series. Chec...
57,Adam Geitgey,15.2K,13,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 4: Modern Face R...,Update: This article is part of a series. Chec...
58,Adam Geitgey,10.4K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 2 – Adam Geitgey...,Update: This article is part of a series. Chec...
60,Adam Geitgey,6.8K,11,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun Part 6: How to do Spee...,Update: This article is part of a series. Chec...
61,Adam Geitgey,5.8K,16,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun Part 5: Language Trans...,Update: This article is part of a series. Chec...
98,Adam Geitgey,10.4K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 2 – Adam Geitgey...,Update: This article is part of a series. Chec...
136,Adam Geitgey,10.4K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 2 – Adam Geitgey...,Update: This article is part of a series. Chec...
138,Adam Geitgey,6.8K,11,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun Part 6: How to do Spee...,Update: This article is part of a series. Chec...
139,Adam Geitgey,5.8K,16,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun Part 5: Language Trans...,Update: This article is part of a series. Chec...
169,Adam Geitgey,14.2K,15,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 3: Deep Learning...,Update: This article is part of a series. Chec...
170,Adam Geitgey,15.2K,13,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun! Part 4: Modern Face R...,Update: This article is part of a series. Chec...

In [90]:
data_f.title=='Chatbots were the next big thing: what happened? – The Startup – Medium'

0       True
1      False
2      False
3      False
4      False
       ...
332    False
333    False
334    False
335    False
336    False
Name: title, Length: 337, dtype: bool

In [26]:
sum(data_f.title=='Chatbots were the next big thing: what happened? – The Startup – Medium')

3

In [27]:
#show them
data_f.loc[data_f.title=='Chatbots were the next big thing: what happened? – The Startup – Medium']

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
86,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
273,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."

In [28]:
(data_f['title']=='Chatbots were the next big thing: what happened? – The Startup – Medium').head()

0     True
1    False
2    False
3    False
4    False
Name: title, dtype: bool

In [29]:
data_f.loc[(data_f.claps=='8.3K')&(data_f.reading_time==11)]

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
86,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
273,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."

In [94]:
data_f.loc[data_f.reading_time==11].shape

(27, 6)

In [95]:
data_f.loc[data_f.reading_time==11]

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
29,Netflix Technology Blog,330,11,https://medium.com/netflix-techblog/system-arc...,System Architectures for Personalization and R...,by Xavier Amatriain and Justin Basilico\nIn ou...
38,AirbnbEng,369,11,https://medium.com/airbnb-engineering/architec...,Architecting a Machine Learning System for Ris...,"By Naseem Hakim & Aaron Keys\nAt Airbnb, we wa..."
60,Adam Geitgey,6.8K,11,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun Part 6: How to do Spee...,Update: This article is part of a series. Chec...
77,James Le,18.4K,11,https://towardsdatascience.com/a-tour-of-the-t...,A Tour of The Top 10 Algorithms for Machine Le...,"In machine learning, there’s something called ..."
80,David Foster,12.8K,11,https://medium.com/applied-data-science/how-to...,How to build your own AlphaZero AI using Pytho...,In this article I’ll attempt to cover three th...
81,George Seif,11.4K,11,https://towardsdatascience.com/the-5-clusterin...,The 5 Clustering Algorithms Data Scientists Ne...,Clustering is a Machine Learning technique tha...
86,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
88,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
96,Matt Schlicht,5K,11,https://chatbotsmagazine.com/the-complete-begi...,The Complete Beginner’s Guide To Chatbots – Ch...,What are chatbots? Why are they such a big opp...
133,Frank Diana,428,11,https://medium.com/@frankdiana/digital-transfo...,Digital Transformation of Business and Society...,"At a recent KPMG Robotic Innovations event, Fu..."
138,Adam Geitgey,6.8K,11,https://medium.com/@ageitgey/machine-learning-...,Machine Learning is Fun Part 6: How to do Spee...,Update: This article is part of a series. Chec...
157,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
177,Netflix Technology Blog,99,11,https://medium.com/netflix-techblog/distribute...,Distributed Neural Networks with GPUs in the A...,"by Alex Chen, Justin Basilico, and Xavier Amat..."
206,David Foster,12.8K,11,https://medium.com/applied-data-science/how-to...,How to build your own AlphaZero AI using Pytho...,In this article I’ll attempt to cover three th...
211,Seth Weidman,2.8K,11,https://hackernoon.com/the-3-tricks-that-made-...,The 3 Tricks That Made AlphaGo Zero Work – Hac...,There were many advances in Deep Learning and ...
212,Gabriel Aldamiz...,5.1K,11,https://hackernoon.com/how-we-grew-from-0-to-4...,How we grew from 0 to 4 million women on our f...,"Three years ago we launched Chicisimo, our goa..."
218,Kai Stinchcombe,44K,11,https://medium.com/@kaistinchcombe/decentraliz...,Blockchain is not only crappy technology but a...,Blockchain is not only crappy technology but a...
224,Kai Stinchcombe,44K,11,https://medium.com/@kaistinchcombe/decentraliz...,Blockchain is not only crappy technology but a...,Blockchain is not only crappy technology but a...
234,Diana Filippova,1,11,https://medium.com/@dnafilippova/de-la-coop%C3...,De la coopération entre les hommes et les mac...,Originally published at www.cuberevue.com on N...
251,Vivek Yadav,425,11,https://chatbotslife.com/using-augmentation-to...,An augmentation based deep neural network appr...,"Overview\nIn this post, we will go over the wo..."
268,Jerry Chen,2.3K,11,https://news.greylock.com/the-new-moats-53f61a...,The New Moats – Greylock Perspectives,To build a sustainable and profitable business...
273,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
316,Dhruv Parthasarathy,665,11,https://medium.com/@dhruvp/how-to-write-a-neur...,Write an AI to win at Pong from scratch with R...,There’s a huge difference between reading abou...
325,Neelabh Pant,2K,11,https://blog.statsbot.co/time-series-predictio...,A Guide For Time Series Prediction Using Recur...,The Statsbot team has already published the ar...

In [96]:
data_f.loc[data_f.claps=='8.3K'].shape

(3, 6)

###### Built-in conditional selectors

In [97]:
# use isin() 
data_f.loc[data_f.reading_time.isin([5,11,12])]

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...
17,Gil Fewster,3.3K,5,https://medium.freecodecamp.org/the-mind-blowi...,The mind-blowing AI announcement from Google t...,Disclaimer: I’m not an expert in neural networ...
29,Netflix Technology Blog,330,11,https://medium.com/netflix-techblog/system-arc...,System Architectures for Personalization and R...,by Xavier Amatriain and Justin Basilico\nIn ou...
...,...,...,...,...,...,...
298,Datafiniti,3,5,https://blog.datafiniti.co/classifying-website...,Classifying Websites with Neural Networks – Kn...,"At Datafiniti, we have a strong need for conve..."
316,Dhruv Parthasarathy,665,11,https://medium.com/@dhruvp/how-to-write-a-neur...,Write an AI to win at Pong from scratch with R...,There’s a huge difference between reading abou...
317,Waleed Abdulla,507,12,https://medium.com/@waleedka/traffic-sign-reco...,Traffic Sign Recognition with TensorFlow – Wal...,This is part 1 of a series about building a de...
324,nafrondel,1.7K,5,https://medium.com/@nafrondel/you-requested-so...,You requested someone with a degree in this? *...,You requested someone with a degree in this? *...
325,Neelabh Pant,2K,11,https://blog.statsbot.co/time-series-predictio...,A Guide For Time Series Prediction Using Recur...,The Statsbot team has already published the ar...

###### Filtering data using query() method
taking expression to filter data, return Filtered Data

In [47]:
data_f.query('reading_time < 5') # return articles have reading time greater than 5

,author,claps,reading_time,link,title,text
10,Sophia Arakelyan,7,4,https://buzzrobot.com/from-ballerina-to-ai-res...,From Ballerina to AI Researcher: Part I – buZZ...,"Last year, I published the article “From Balle..."
21,Eran Kampf,57,3,https://developerzen.com/data-mining-handling-...,Data Mining — Handling Missing Values the Data...,I’ve recently answered Predicting missing data...
23,Xu Wenhao,1,4,https://xuwenhao.com/%E5%BB%BA%E8%AE%AE%E7%9A%...,建议的程序员学习LDA算法的步骤 – 蒸汽与魔法,"这一阵为了工作上的关系,花了点时间学习了一下LDA算法,说实话,对于我这个学CS而非学数学的..."
34,Akash Shende,1,3,https://medium.com/@akash0x53/color-based-obje...,Color Based Object Segmentation – Akash Shende...,"In this picture, Pranav Mistry is using color ..."
35,Hrishikesh Huilgolkar,1,4,https://medium.com/@hrishikeshio/traveling-san...,Traveling santa Problem — An incompetent algor...,Kaggle announced the Traveling santa problem i...
41,Nikhil Dandekar,116,3,https://towardsdatascience.com/what-makes-a-go...,What makes a good data scientist/engineer? – T...,The term data scientist has been used lately t...
49,Matt Fogel,938,4,https://medium.com/swlh/the-7-best-data-scienc...,The 7 Best Data Science and Machine Learning P...,Data science and machine learning have long be...
50,Illia Polosukhin,255,3,https://medium.com/@ilblackdragon/tensorflow-t...,TensorFlow Tutorial— Part 1 – Illia Polosukhin...,"UPD (April 20, 2016): Scikit Flow has been mer..."
51,Ahmed El Deeb,283,3,https://medium.com/rants-on-machine-learning/t...,The Unreasonable Effectiveness of Random Fores...,It’s very common for machine learning practiti...
52,Christophe Bourguignat,157,4,https://medium.com/@chris_bour/6-tricks-i-lear...,6 Tricks I Learned From The OTTO Kaggle Challe...,Here are a few things I learned from the OTTO ...
53,I'Boss Potiwarakorn,128,3,https://medium.com/o-v-e-r-f-i-t-t-e-d/machine...,"Machine Learning เรียนอะไร, รู้ไปทําไม – O v e...",Machine Learning จริงๆแล้วมันคืออะไรกันแน่? คร...
54,samim,301,4,https://medium.com/@samim/generating-stories-a...,Generating Stories about Images – samim – Medium,Stories are a fundamental human tool that we u...
95,Sophia Arakelyan,7,4,https://buzzrobot.com/from-ballerina-to-ai-res...,From Ballerina to AI Researcher: Part I – buZZ...,"Last year, I published the article “From Balle..."
102,Greg Fish,1,4,https://worldofweirdthings.com/looking-for-a-g...,looking for a ghost in the machine – [ weird t...,"A short while ago, I wrote about some of the c..."
104,Greg Fish,1,4,https://worldofweirdthings.com/the-technical-t...,the technical trouble with humanoid robots – [...,"If you’ve been reading this blog long enough, ..."
109,Greg Fish,1,4,https://worldofweirdthings.com/why-you-just-ca...,why you just can’t black box an a.i. – [ weird...,Singularitarians generally believe two things ...
110,Greg Fish,2,3,https://worldofweirdthings.com/why-do-we-want-...,why do we want to build a fully fledged a.g.i....,Undoubtedly the most ambitious idea in the wor...
113,Theo,3,4,https://becominghuman.ai/is-there-a-future-for...,Is there a future for innovation ? – Becoming ...,Have you noticed how tech savvy children have ...
114,x.ai,1,2,https://medium.com/@xdotai/i-scheduled-1-019-m...,"I scheduled 1,019 meetings in 2012 — and that ...",The number of meetings that I scheduled in 201...
120,Joe Johnston,38,4,https://medium.com/universal-mind/how-i-tracke...,How I tracked my house movements using iBeacon...,Recently I’ve started experimenting more and m...
122,Pandorabots,14,3,https://medium.com/pandorabots-blog/using-oob-...,Using OOB Tags in AIML: Part I – pandorabots-b...,Suppose you are building an Intelligent Virtua...
123,Denny Vrandečić,4,4,https://medium.com/@vrandezo/ai-is-coming-and-...,"AI is coming, and it will be boring – Denny Vr...","I was asked about my opinion on this topic, an..."
131,Milo Spencer-Harper,2.2K,3,https://medium.com/technology-invention-and-mo...,How to build a multi-layered neural network in...,"In my last blog post, thanks to an excellent b..."
164,Abhishek Parbhakar,1.7K,3,https://towardsdatascience.com/why-data-scient...,Why Data Scientists love Gaussian? – Towards D...,For Deep Learning & Machine Learning engineers...
167,Erick Muzart Fonseca dos Santos,16,2,https://medium.com/deeplearningbrasilia/o-grup...,O Grupo de Estudo em Deep Learning de Brasíli...,O Grupo de Estudo em Deep Learning de Brasíli...
178,Francesco Gadaleta,3,4,https://hackernoon.com/gradient-descent-vs-coo...,Gradient descent vs coordinate descent – Hacke...,"When it comes to function minimization, it’s t..."
179,Milo Spencer-Harper,2.2K,3,https://medium.com/technology-invention-and-mo...,How to build a multi-layered neural network in...,"In my last blog post, thanks to an excellent b..."
180,Jim Fleming,294,3,https://medium.com/jim-fleming/loading-a-tenso...,Loading a TensorFlow graph with the C++ API – ...,Check out the related post: Loading TensorFlow...
181,Milo Spencer-Harper,1.8K,4,https://medium.com/deep-learning-101/how-to-ge...,Video of a neural network learning – Deep Lear...,"As part of my quest to learn about AI, I gener..."
184,Illia Polosukhin,108,3,https://medium.com/@ilblackdragon/tensorflow-t...,Tensorflow Tutorial — Part 2 – Illia Polosukhi...,"In the previous Part 1 of this tutorial, I int..."
187,Jim Fleming,165,4,https://medium.com/jim-fleming/highway-network...,Highway Networks with TensorFlow – Jim Fleming...,This week I implemented highway networks to ge...
210,Bargava,11.8K,3,https://towardsdatascience.com/how-to-learn-de...,How to learn Deep Learning in 6 months – Towar...,"It is quite possible to learn, follow and cont..."
219,savedroid ICO,340,3,https://medium.com/@ico_8796/sneakpeek-the-sav...,#SNEAKPEEK The savedroid crypto saving app — P...,The international beta of our brand new crypto...
233,Theo,3,4,https://becominghuman.ai/is-there-a-future-for...,Is there a future for innovation ? – Becoming ...,Have you noticed how tech savvy children have ...
239,Matt Wiese,4,3,https://medium.com/@mattwiese/digital-companio...,Digital Companionship – Matt Wiese – Medium,"Recently, I chose to treat myself to a movie I..."
242,James Cooper,57,3,https://render.betaworks.com/announcing-poncho...,Announcing Poncho the WeatherBot – Render-from...,You can now get personal weather forecasts in ...
245,iDanScott,3,4,https://medium.com/@iDanScott/the-bejeweled-so...,C# Plays Bejeweled Blitz – iDanScott – Medium,As some of you reading this may or may not alr...
281,Amine Aoullay,58,4,https://towardsdatascience.com/how-to-use-nois...,How to use Noise to your advantage ? – Towards...,"For scientists, random fluctuations, or noise ..."
287,Wallarm,72,4,https://lab.wallarm.com/tensorflow-dataset-api...,TensorFlow Dataset API for increasing training...,Wallarm AI engine is the heart of our security...
289,Amine Aoullay,58,4,https://towardsdatascience.com/how-to-use-nois...,How to use Noise to your advantage ? – Towards...,"For scientists, random fluctuations, or noise ..."
300,Milo Spencer-Harper,2.2K,3,https://medium.com/technology-invention-and-mo...,How to build a multi-layered neural network in...,"In my last blog post, thanks to an excellent b..."
304,Milo Spencer-Harper,42,3,https://medium.com/@miloharper/thanks-so-much-...,Thanks so much for your response Jared. Really...,Thanks so much for your response Jared. Really...
306,Dr Ben Medlock,32,4,https://medium.com/@Ben_Medlock/why-turing-s-l...,Why Turing’s legacy demands a smarter keyboard...,Why Turing’s legacy demands a smarter keyboard...
330,Oleksandr Savsunenko,5.5K,4,https://hackernoon.com/the-new-neural-internet...,The New Neural Internet is Coming – Hacker Noon,How it all began / The Landscape\nThink of the...
334,Devin Soni,5.8K,4,https://towardsdatascience.com/spiking-neural-...,"Spiking Neural Networks, the Next Generation o...",Everyone who has been remotely tuned in to rec...

**Q:** in data ('medium_data.csv')
- count of only the articles where the number of claps is greater than 1000.
- Select only the articles that it is publicated by Towards Data Science where the number of claps is greater than 1000.

###### Assigning data

In [98]:
len(data_f)

337

In [99]:
# add column
import numpy as np
data_f['num_comments']=np.random.randint(1,50,len(data_f))
data_f.head()

,author,claps,reading_time,link,title,text,num_comments
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T...",35
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...,44
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...,40
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...,1
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...,45

In [30]:
len(data_f)

337

**Q:** change value of column `id`  into numbers that has mean = 0.0 in data ('medium_data.csv').

###### Drop specified labels from rows or columns.

In [101]:
# we can remove rows or columns from data by drop()
data_f.drop(['num_comments'], axis=1,inplace=True)
data_f.head()

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...

##### Maps
It is possible to iterate over a DataFrame or Series as you would with a list, but doing so — especially on large datasets — is very slow.

map is function that takes one set of values and "maps" them to another set of values.
We can transform data from the format it is in now to the format that we want it using Maps.


- `apply` method can be applied both to series and dataframes,if we want to transform a whole DataFrame by calling a custom method on each row.

###### NOTE:
 `apply` don't modify the original data they're called on

In [103]:
def str_to_float(strk):
    return float(strk[:-1]) if 'K'in strk else float(strk)/1000.0
    
str_to_float('599')

0.599

In [104]:
data_f.loc[:,'claps'].head()

0    8.3K
1    1.4K
2    2.8K
3    1.3K
4     935
Name: claps, dtype: object

In [105]:
data_f.loc[:,'claps'].apply(str_to_float)

0      8.300
1      1.400
2      2.800
3      1.300
4      0.935
       ...
332    3.400
333    2.800
334    5.800
335    3.900
336    2.400
Name: claps, Length: 337, dtype: float64

In [106]:
def str_to_float2(row):
    return float(row.claps[:-1]) if 'K'in row.claps else float(row.claps)/1000.0


data_f.apply(str_to_float2, axis=1)

0      8.300
1      1.400
2      2.800
3      1.300
4      0.935
       ...
332    3.400
333    2.800
334    5.800
335    3.900
336    2.400
Length: 337, dtype: float64

#### Grouping
`groupby()` function is used to split the data into groups based on some criteria.

In [32]:
data_f.head(3)

,author,claps,reading_time,link,title,text
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T..."
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...

In [33]:
data_f.loc[data_f.author=='Abhishek Parbhakar']

,author,claps,reading_time,link,title,text
8,Abhishek Parbhakar,937,6,https://towardsdatascience.com/must-know-infor...,Must know Information Theory concepts in Deep ...,Information theory is an important field that ...
92,Abhishek Parbhakar,937,6,https://towardsdatascience.com/must-know-infor...,Must know Information Theory concepts in Deep ...,Information theory is an important field that ...
159,Abhishek Parbhakar,937,6,https://towardsdatascience.com/must-know-infor...,Must know Information Theory concepts in Deep ...,Information theory is an important field that ...
164,Abhishek Parbhakar,1.7K,3,https://towardsdatascience.com/why-data-scient...,Why Data Scientists love Gaussian? – Towards D...,For Deep Learning & Machine Learning engineers...

In [34]:
sdata=data_f.groupby('author').sum() #sum values of reading_time for each author

In [35]:
sdata

                    reading_time
author
Abhishek Parbhakar            21
Adam Geitgey                 228
Ahmed El Deeb                 10
AirbnbEng                     20
Akash Shende                   3
...                          ...
nafrondel                      5
paulson                       17
samim                         12
savedroid ICO                  3
x.ai                           2

[182 rows x 1 columns]

In [36]:
sdata.sort_values('reading_time',ascending=False)

                                 reading_time
author
Adam Geitgey                              228
Slav Ivanov                               133
David Venturi                              80
Dhruv Parthasarathy                        71
Tim Anglade                                69
...                                       ...
Matt Wiese                                  3
Nikhil Dandekar                             3
Pandorabots                                 3
Erick Muzart Fonseca dos Santos             2
x.ai                                        2

[182 rows x 1 columns]

In [38]:
data_f.index

RangeIndex(start=0, stop=337, step=1)

###### Q: Get the least reading time in each title articles category in data ('medium_data.csv').

###### Combining:
we use `concat()` to combine two dataframe and Given a list of dataframe .

In [39]:
data_f2=pd.read_csv('../data/medium_data.csv',nrows=100)# set The same number of rows of data_f ===> data_f.shape[0]

In [42]:
article_data=pd.concat([data_f, data_f2])
article_data.head()

,author,claps,reading_time,link,title,text,id,url,subtitle,image,responses,publication,date
0,Justin Lee,8.3K,11,https://medium.com/swlh/chatbots-were-the-next...,Chatbots were the next big thing: what happene...,"Oh, how the headlines blared:\nChatbots were T...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Conor Dewey,1.4K,7,https://towardsdatascience.com/python-for-data...,Python for Data Science: 8 Concepts You May Ha...,If you’ve ever found yourself looking up the s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,William Koehrsen,2.8K,11,https://towardsdatascience.com/automated-featu...,Automated Feature Engineering in Python – Towa...,Machine learning is increasingly moving from h...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Gant Laborde,1.3K,7,https://medium.freecodecamp.org/machine-learni...,Machine Learning: how to go from Zero to Hero ...,If your understanding of A.I. and Machine Lear...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Emmanuel Ameisen,935,11,https://blog.insightdatascience.com/reinforcem...,Reinforcement Learning from scratch – Insight ...,Want to learn about applied Artificial Intelli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

###### Dealing with Missing Data 
Entries missing values are given the value NaN.

To select NaN entries we can use `isnull()` .

To remove all columns or rows that contain least one missing value we can use `dropna()` .

To fill in missing values in a dataframe OR specify what we want the NaN values to be replaced with we can use `fillna()` .

In [44]:
article_data.isnull().sum()

author          100
claps             0
reading_time      0
link            100
title             0
text            100
id              337
url             337
subtitle        385
image           339
responses       337
publication     337
date            337
dtype: int64

In [45]:
#article_data.dropna() #remove all the rows that contain a missing value
article_data.dropna(axis=1) #remove all columns with at least one missing value

   claps  reading_time                                              title
0   8.3K            11  Chatbots were the next big thing: what happene...
1   1.4K             7  Python for Data Science: 8 Concepts You May Ha...
2   2.8K            11  Automated Feature Engineering in Python – Towa...
3   1.3K             7  Machine Learning: how to go from Zero to Hero ...
4    935            11  Reinforcement Learning from scratch – Insight ...
..   ...           ...                                                ...
95     7             6  How to Live in the Present and Make Your Time ...
96    77             7                                 Look ma, no hands!
97    37             6    Raised on Nintendo 64: My Story on Bilingualism
98   111             4              I Don’t Know What To Do With My Hands
99    64             7  3 Tips for Sticking to New Habits When Travelling

[437 rows x 3 columns]

In [46]:
article_data.loc[:,['id','url','responses','publication','date']].fillna("Unknown")

,id,url,responses,publication,date
0,Unknown,Unknown,Unknown,Unknown,Unknown
1,Unknown,Unknown,Unknown,Unknown,Unknown
2,Unknown,Unknown,Unknown,Unknown,Unknown
3,Unknown,Unknown,Unknown,Unknown,Unknown
4,Unknown,Unknown,Unknown,Unknown,Unknown
...,...,...,...,...,...
95,96.0,https://medium.com/swlh/how-to-live-in-the-pre...,0.0,The Startup,2019-05-30
96,97.0,https://medium.com/swlh/look-ma-no-hands-3ddef...,0.0,The Startup,2019-05-30
97,98.0,https://medium.com/swlh/raised-on-nintendo-64-...,3.0,The Startup,2019-05-30
98,99.0,https://medium.com/swlh/i-dont-know-what-to-do...,0.0,The Startup,2019-05-30
99,100.0,https://medium.com/swlh/3-tips-for-sticking-to...,0.0,The Startup,2019-05-30

**Q:** Replace Missing Data in `subtitle` by text='no subtitle'  in data ('medium_data.csv').